### PR TITLE
feat: all members

### PR DESCRIPTION
**Pull request by msp5382**

### CODE REVIEW

**Comment by new5558** [comment]
We should have prettierrc file!

**Comment by bombnp** [comment]
Yea i was about to ask that

**Comment by msp5382** [comment]
sry I forgot to turn off format on save;-;

**Comment by new5558** [comment]
Just merged the new prettier formatting to master (newer than msp5382/thinc-www@36cf97e). Please update this branch with master krub.

**Review by new5558 — APPROVED** [review]
LGTM

**Pull request merged**
